<a href="https://colab.research.google.com/github/akshayugalmogale/Neural-Networks-and-Deep-Learning-Practice/blob/main/Word_Embedding_Techniques_using_Embedding_layer_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=1000

One Hot Representation

In [6]:
onehot_reps=[one_hot(words,voc_size)for words in sent]
print(onehot_reps)

[[271, 379, 345, 967], [271, 379, 345, 39], [271, 692, 345, 718], [883, 338, 496, 99, 964], [883, 338, 496, 99, 62], [301, 271, 778, 345, 317], [22, 337, 959, 99]]


Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

In [10]:
sent_length=8

In [24]:
embedded_doc=pad_sequences(onehot_reps,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[  0   0   0   0 271 379 345 967]
 [  0   0   0   0 271 379 345  39]
 [  0   0   0   0 271 692 345 718]
 [  0   0   0 883 338 496  99 964]
 [  0   0   0 883 338 496  99  62]
 [  0   0   0 301 271 778 345 317]
 [  0   0   0   0  22 337 959  99]]


In [13]:
dim=15

In [27]:
from tensorflow.keras.models import Sequential
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 15)             15000     
                                                                 
Total params: 15,000
Trainable params: 15,000
Non-trainable params: 0
_________________________________________________________________


In [30]:
print(model.predict(embedded_doc))

1/1 [==============================] - 0s 278ms/step
[[[-3.33857089e-02 -3.58735099e-02  6.23115152e-03  2.69858502e-02
    3.11180614e-02  3.36668529e-02  4.75708395e-03 -1.42746679e-02
   -3.47588435e-02  2.92313136e-02  1.71763636e-02  2.18415000e-02
    1.09068751e-02 -3.18668112e-02  3.61348502e-02]
  [-3.33857089e-02 -3.58735099e-02  6.23115152e-03  2.69858502e-02
    3.11180614e-02  3.36668529e-02  4.75708395e-03 -1.42746679e-02
   -3.47588435e-02  2.92313136e-02  1.71763636e-02  2.18415000e-02
    1.09068751e-02 -3.18668112e-02  3.61348502e-02]
  [-3.33857089e-02 -3.58735099e-02  6.23115152e-03  2.69858502e-02
    3.11180614e-02  3.36668529e-02  4.75708395e-03 -1.42746679e-02
   -3.47588435e-02  2.92313136e-02  1.71763636e-02  2.18415000e-02
    1.09068751e-02 -3.18668112e-02  3.61348502e-02]
  [-3.33857089e-02 -3.58735099e-02  6.23115152e-03  2.69858502e-02
    3.11180614e-02  3.36668529e-02  4.75708395e-03 -1.42746679e-02
   -3.47588435e-02  2.92313136e-02  1.71763636e-02  2.

In [32]:
embedded_doc[0]

array([  0,   0,   0,   0, 271, 379, 345, 967], dtype=int32)

In [31]:
print(model.predict(embedded_doc[0]))

1/1 [==============================] - 0s 74ms/step
[[-0.03338571 -0.03587351  0.00623115  0.02698585  0.03111806  0.03366685
   0.00475708 -0.01427467 -0.03475884  0.02923131  0.01717636  0.0218415
   0.01090688 -0.03186681  0.03613485]
 [-0.03338571 -0.03587351  0.00623115  0.02698585  0.03111806  0.03366685
   0.00475708 -0.01427467 -0.03475884  0.02923131  0.01717636  0.0218415
   0.01090688 -0.03186681  0.03613485]
 [-0.03338571 -0.03587351  0.00623115  0.02698585  0.03111806  0.03366685
   0.00475708 -0.01427467 -0.03475884  0.02923131  0.01717636  0.0218415
   0.01090688 -0.03186681  0.03613485]
 [-0.03338571 -0.03587351  0.00623115  0.02698585  0.03111806  0.03366685
   0.00475708 -0.01427467 -0.03475884  0.02923131  0.01717636  0.0218415
   0.01090688 -0.03186681  0.03613485]
 [-0.01109546 -0.02009754 -0.01038289  0.01188838 -0.01147968 -0.04573212
   0.01397362 -0.00450742  0.04323877 -0.00151681 -0.03556694 -0.04842976
   0.01579927 -0.02220999  0.0035814 ]
 [ 0.01848425 -0.